/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-118579-gbb87d19cd9-20250228"
#endif /* AVUTIL_FFVERSION_H */
